var config = {
  translations: {
    language: 'en',
    welcome: 'Welcome',
    be_glad: 'We will be glad if you fill out the following data',
    skip: 'Skip and continue with',
    facebook: 'Login with facebook',
    or_fill: 'fill out the following data',
    full_name: 'Full name',
    email: 'Email',
    adress: 'Adress',
    continue: 'Continue',
    selfies: 'Want to make selfies',
    or: 'or',
    want: 'Yes, I want, go foto',
    not_now: 'Not now',
    back: 'Back',
    man: 'Man',
    woman: 'Woman',
    last_data: 'Last data and finish',
    date_of_birth: 'Date of birth',
    source: 'Source',
    remarks_and_preferences: 'Remarks and preferences',
    confirm: 'Confirm',
    recommended_by: 'Recommended by:',
    customers_agree: 'Check here to indicate that you have read and agree to the terms of the Atzma.in Customer Agreement',
    thanks: 'Thanks!',
    glad_see: 'We are glad to see you',
    close: 'Close',
    source_list: [
      {value: 'ads', label: 'Ads'},
      {value: 'fb_page', label: 'fb_page'},
      {value: 'family', label: 'family'},
      {value: 'friends', label: 'friends'},
      {value: 'recommendation', label: 'recommendation'}
    ]
  },
  urls: {
    adress: 'https://maps.googleapis.com/maps/api/geocode/json?address={query}&language={language}',
    add_client_url: '/add-client/clients?q={query}',
    main: 'https://api.bewebmaster.co.il',
    photo_r: '/filling-up/photo',
    notes: '/filling-up/notes',
    other_data: '/other_data',
    filling_up: '/filling-up',
    last_page: '/last_page',
    media: './dist/media/',
    photo: '/photo',
    home: '/',
    baseUrl: '',
    params: '?b=123&c=sdfs2d1f'
  },
  data: {
    name: '',
    email: '',
    address: '',
    photo: '',
    gender: '',
    birthdate: '',
    source: '',
    note: '',
    permit_ads: false
  },
  isRtL: false,
  address_based: true,
  greetings_text: 'We`re so glad to see you our friend, your next visit you`ll get 20% discount. Remember, every client is our family',
  business_name: 'Beauty Salon Maria',
  business_adress: 'Tel Aviv, Allenby str. 45',
  business_desc: 'loresdfgs dgsdgsdf ffffffffffffff ffffffffs  sdgsd sd sg sgdfffffffffff sdfg sdf sd gsdf s sfgs dfgsf sd sg dsfm',
  business_links: [{icon: 'facebook-icon.png', url: '/facebook_url'}, {icon: 'website.png', url: '/website'}],
  plugins: ['highres_photos'],
  timeout: 500,
  max_side: 1000
}
